name: Build and test
on: push
jobs:
   gfortran:
      strategy:
         matrix:
            version: [9, 10, 11, 12]
            os: [ubuntu-latest]
#            include:
#               - version: 6
#                 os: ubuntu-18.04
#               - version: 8
#                 cmake_args: -DFABM_USE_CONTIGUOUS=OFF
         fail-fast: false
      runs-on: ${{ matrix.os }}
      steps:
      - name: Install compiler
        run: |
           sudo apt-get update
           sudo apt-get install gfortran-${{ matrix.version }}
      - name: Clone gsw
        uses: actions/checkout@v2
      - name: Build and run all test cases
#        run: python3 cases/scripts/run_all.py --show_logs --gotm_base=gotm --exclude plume --compiler=gfortran-${{ matrix.version }} -DGOTM_USE_STIM=ON -DGOTM_USE_SEAGRASS=ON -DGOTM_USE_NetCDF=OFF ${{ matrix.cmake_args }}
