name: Build and test
on: push
jobs:
   gfortran:
      strategy:
         matrix:
            version: [9, 10, 11, 12]
            os: [ubuntu-latest]
#            include:
#               - version: 6
#                 os: ubuntu-18.04
#               - version: 8
#                 cmake_args: -DFABM_USE_CONTIGUOUS=OFF
         fail-fast: false
      runs-on: ${{ matrix.os }}
      steps:
      - name: Install compiler
        run: |
           sudo apt-get update
           sudo apt-get install gfortran-${{ matrix.version }} cmake
      - name: Clone gsw
        uses: actions/checkout@v2
      - name: Build
        run: cmake . -DCMAKE_Fortran_COMPILER=gfortran-${{ matrix.version }}
